/**
 * @author Walter Gugenberger
 * @date 06.06.2013 19:18:51
 * @version
 * @name guide.org.noip.wuidl.tourguide.api.wsdl.weather.WeatherSoap.java
 * @description WeatherSoap
 */
package org.noip.wuidl.tourguide.api.wsdl.weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-05T19:20:33.004+02:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://ws.cdyne.com/WeatherWS/", name = "WeatherSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherSoap {

    /**
	 * Gets Information for each WeatherID.
	 * 
	 * @return the weather information
	 */
    @WebResult(name = "GetWeatherInformationResult", targetNamespace = "http://ws.cdyne.com/WeatherWS/")
    @RequestWrapper(localName = "GetWeatherInformation", targetNamespace = "http://ws.cdyne.com/WeatherWS/", className = "org.noip.wuidl.tourguide.api.wsdl.weather.GetWeatherInformation")
    @WebMethod(operationName = "GetWeatherInformation", action = "http://ws.cdyne.com/WeatherWS/GetWeatherInformation")
    @ResponseWrapper(localName = "GetWeatherInformationResponse", targetNamespace = "http://ws.cdyne.com/WeatherWS/", className = "org.noip.wuidl.tourguide.api.wsdl.weather.GetWeatherInformationResponse")
    public org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfWeatherDescription getWeatherInformation();

    /**
	 * Allows you to get your City's Weather, which is updated hourly. U.S. Only
	 * 
	 * @param zip
	 *            the zip
	 * @return the city weather by zip
	 */
    @WebResult(name = "GetCityWeatherByZIPResult", targetNamespace = "http://ws.cdyne.com/WeatherWS/")
    @RequestWrapper(localName = "GetCityWeatherByZIP", targetNamespace = "http://ws.cdyne.com/WeatherWS/", className = "org.noip.wuidl.tourguide.api.wsdl.weather.GetCityWeatherByZIP")
    @WebMethod(operationName = "GetCityWeatherByZIP", action = "http://ws.cdyne.com/WeatherWS/GetCityWeatherByZIP")
    @ResponseWrapper(localName = "GetCityWeatherByZIPResponse", targetNamespace = "http://ws.cdyne.com/WeatherWS/", className = "org.noip.wuidl.tourguide.api.wsdl.weather.GetCityWeatherByZIPResponse")
    public org.noip.wuidl.tourguide.api.wsdl.weather.WeatherReturn getCityWeatherByZIP(
        @WebParam(name = "ZIP", targetNamespace = "http://ws.cdyne.com/WeatherWS/")
        java.lang.String zip
    );

    /**
	 * Allows you to get your City Forecast Over the Next 7 Days, which is
	 * updated hourly. U.S. Only
	 * 
	 * @param zip
	 *            the zip
	 * @return the city forecast by zip
	 */
    @WebResult(name = "GetCityForecastByZIPResult", targetNamespace = "http://ws.cdyne.com/WeatherWS/")
    @RequestWrapper(localName = "GetCityForecastByZIP", targetNamespace = "http://ws.cdyne.com/WeatherWS/", className = "org.noip.wuidl.tourguide.api.wsdl.weather.GetCityForecastByZIP")
    @WebMethod(operationName = "GetCityForecastByZIP", action = "http://ws.cdyne.com/WeatherWS/GetCityForecastByZIP")
    @ResponseWrapper(localName = "GetCityForecastByZIPResponse", targetNamespace = "http://ws.cdyne.com/WeatherWS/", className = "org.noip.wuidl.tourguide.api.wsdl.weather.GetCityForecastByZIPResponse")
    public org.noip.wuidl.tourguide.api.wsdl.weather.ForecastReturn getCityForecastByZIP(
        @WebParam(name = "ZIP", targetNamespace = "http://ws.cdyne.com/WeatherWS/")
        java.lang.String zip
    );
}
