
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.noip.wuidl.tourguide.api.wsdl.weather;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-05T19:20:32.929+02:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "Weather",
                      portName = "WeatherHttpGet",
                      targetNamespace = "http://ws.cdyne.com/WeatherWS/",
                      wsdlLocation = "http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL",
                      endpointInterface = "org.noip.wuidl.tourguide.api.wsdl.weather.WeatherHttpGet")
                      
public class WeatherHttpGetImpl implements WeatherHttpGet {

    /** The Constant LOG. */
    private static final Logger LOG = Logger.getLogger(WeatherHttpGetImpl.class.getName());

    /* (non-Javadoc)
     * @see org.noip.wuidl.tourguide.api.wsdl.weather.WeatherHttpGet#getWeatherInformation(*
     */
    public org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfWeatherDescription getWeatherInformation() { 
        LOG.info("Executing operation getWeatherInformation");
        try {
            org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfWeatherDescription _return = new org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfWeatherDescription();
            java.util.List<org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription> _returnWeatherDescription = new java.util.ArrayList<org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription>();
            org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription _returnWeatherDescriptionVal1 = new org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription();
            _returnWeatherDescriptionVal1.setWeatherID((short)-30391);
            _returnWeatherDescriptionVal1.setDescription("Description877716487");
            _returnWeatherDescriptionVal1.setPictureURL("PictureURL1652470334");
            _returnWeatherDescription.add(_returnWeatherDescriptionVal1);
            _return.getWeatherDescription().addAll(_returnWeatherDescription);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.noip.wuidl.tourguide.api.wsdl.weather.WeatherHttpGet#getCityWeatherByZIP(java.lang.String  zip )*
     */
    public org.noip.wuidl.tourguide.api.wsdl.weather.WeatherReturn getCityWeatherByZIP(java.lang.String zip) { 
        LOG.info("Executing operation getCityWeatherByZIP");
        System.out.println(zip);
        try {
            org.noip.wuidl.tourguide.api.wsdl.weather.WeatherReturn _return = new org.noip.wuidl.tourguide.api.wsdl.weather.WeatherReturn();
            _return.setSuccess(false);
            _return.setResponseText("ResponseText1843572332");
            _return.setState("State-736449371");
            _return.setCity("City2099540256");
            _return.setWeatherStationCity("WeatherStationCity-303414325");
            _return.setWeatherID((short)-12765);
            _return.setDescription("Description-28025668");
            _return.setTemperature("Temperature-505552274");
            _return.setRelativeHumidity("RelativeHumidity1133855674");
            _return.setWind("Wind-1226820678");
            _return.setPressure("Pressure1893136587");
            _return.setVisibility("Visibility790645011");
            _return.setWindChill("WindChill417037185");
            _return.setRemarks("Remarks1880420050");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.noip.wuidl.tourguide.api.wsdl.weather.WeatherHttpGet#getCityForecastByZIP(java.lang.String  zip )*
     */
    public org.noip.wuidl.tourguide.api.wsdl.weather.ForecastReturn getCityForecastByZIP(java.lang.String zip) { 
        LOG.info("Executing operation getCityForecastByZIP");
        System.out.println(zip);
        try {
            org.noip.wuidl.tourguide.api.wsdl.weather.ForecastReturn _return = new org.noip.wuidl.tourguide.api.wsdl.weather.ForecastReturn();
            _return.setSuccess(false);
            _return.setResponseText("ResponseText941810345");
            _return.setState("State-179360835");
            _return.setCity("City-866527064");
            _return.setWeatherStationCity("WeatherStationCity-732443606");
            org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfForecast _returnForecastResult = new org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfForecast();
            java.util.List<org.noip.wuidl.tourguide.api.wsdl.weather.Forecast> _returnForecastResultForecast = new java.util.ArrayList<org.noip.wuidl.tourguide.api.wsdl.weather.Forecast>();
            org.noip.wuidl.tourguide.api.wsdl.weather.Forecast _returnForecastResultForecastVal1 = new org.noip.wuidl.tourguide.api.wsdl.weather.Forecast();
            _returnForecastResultForecastVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-06-05T19:20:32.953+02:00"));
            _returnForecastResultForecastVal1.setWeatherID((short)-18333);
            _returnForecastResultForecastVal1.setDesciption("Desciption-1121894011");
            org.noip.wuidl.tourguide.api.wsdl.weather.Temp _returnForecastResultForecastVal1Temperatures = new org.noip.wuidl.tourguide.api.wsdl.weather.Temp();
            _returnForecastResultForecastVal1Temperatures.setMorningLow("MorningLow54012317");
            _returnForecastResultForecastVal1Temperatures.setDaytimeHigh("DaytimeHigh-2040283413");
            _returnForecastResultForecastVal1.setTemperatures(_returnForecastResultForecastVal1Temperatures);
            org.noip.wuidl.tourguide.api.wsdl.weather.POP _returnForecastResultForecastVal1ProbabilityOfPrecipiation = new org.noip.wuidl.tourguide.api.wsdl.weather.POP();
            _returnForecastResultForecastVal1ProbabilityOfPrecipiation.setNighttime("Nighttime-1062069716");
            _returnForecastResultForecastVal1ProbabilityOfPrecipiation.setDaytime("Daytime514071739");
            _returnForecastResultForecastVal1.setProbabilityOfPrecipiation(_returnForecastResultForecastVal1ProbabilityOfPrecipiation);
            _returnForecastResultForecast.add(_returnForecastResultForecastVal1);
            _returnForecastResult.getForecast().addAll(_returnForecastResultForecast);
            _return.setForecastResult(_returnForecastResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
