
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.noip.wuidl.tourguide.api.wsdl.weather;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-05T19:20:32.971+02:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "Weather",
                      portName = "WeatherSoap",
                      targetNamespace = "http://ws.cdyne.com/WeatherWS/",
                      wsdlLocation = "http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL",
                      endpointInterface = "org.noip.wuidl.tourguide.api.wsdl.weather.WeatherSoap")
                      
public class WeatherSoapImpl1 implements WeatherSoap {

    /** The Constant LOG. */
    private static final Logger LOG = Logger.getLogger(WeatherSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see org.noip.wuidl.tourguide.api.wsdl.weather.WeatherSoap#getWeatherInformation(*
     */
    public org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfWeatherDescription getWeatherInformation() { 
        LOG.info("Executing operation getWeatherInformation");
        try {
            org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfWeatherDescription _return = new org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfWeatherDescription();
            java.util.List<org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription> _returnWeatherDescription = new java.util.ArrayList<org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription>();
            org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription _returnWeatherDescriptionVal1 = new org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription();
            _returnWeatherDescriptionVal1.setWeatherID((short)6829);
            _returnWeatherDescriptionVal1.setDescription("Description-134670527");
            _returnWeatherDescriptionVal1.setPictureURL("PictureURL739183065");
            _returnWeatherDescription.add(_returnWeatherDescriptionVal1);
            _return.getWeatherDescription().addAll(_returnWeatherDescription);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.noip.wuidl.tourguide.api.wsdl.weather.WeatherSoap#getCityWeatherByZIP(java.lang.String  zip )*
     */
    public org.noip.wuidl.tourguide.api.wsdl.weather.WeatherReturn getCityWeatherByZIP(java.lang.String zip) { 
        LOG.info("Executing operation getCityWeatherByZIP");
        System.out.println(zip);
        try {
            org.noip.wuidl.tourguide.api.wsdl.weather.WeatherReturn _return = new org.noip.wuidl.tourguide.api.wsdl.weather.WeatherReturn();
            _return.setSuccess(true);
            _return.setResponseText("ResponseText510770191");
            _return.setState("State1460768527");
            _return.setCity("City2000357658");
            _return.setWeatherStationCity("WeatherStationCity-1323100027");
            _return.setWeatherID((short)20574);
            _return.setDescription("Description514515299");
            _return.setTemperature("Temperature-1780547239");
            _return.setRelativeHumidity("RelativeHumidity549624675");
            _return.setWind("Wind-1670922782");
            _return.setPressure("Pressure-1821139320");
            _return.setVisibility("Visibility-2051685559");
            _return.setWindChill("WindChill-1691039625");
            _return.setRemarks("Remarks821899190");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.noip.wuidl.tourguide.api.wsdl.weather.WeatherSoap#getCityForecastByZIP(java.lang.String  zip )*
     */
    public org.noip.wuidl.tourguide.api.wsdl.weather.ForecastReturn getCityForecastByZIP(java.lang.String zip) { 
        LOG.info("Executing operation getCityForecastByZIP");
        System.out.println(zip);
        try {
            org.noip.wuidl.tourguide.api.wsdl.weather.ForecastReturn _return = new org.noip.wuidl.tourguide.api.wsdl.weather.ForecastReturn();
            _return.setSuccess(false);
            _return.setResponseText("ResponseText-1263699062");
            _return.setState("State-1025062436");
            _return.setCity("City1242147463");
            _return.setWeatherStationCity("WeatherStationCity-1262679882");
            org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfForecast _returnForecastResult = new org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfForecast();
            java.util.List<org.noip.wuidl.tourguide.api.wsdl.weather.Forecast> _returnForecastResultForecast = new java.util.ArrayList<org.noip.wuidl.tourguide.api.wsdl.weather.Forecast>();
            org.noip.wuidl.tourguide.api.wsdl.weather.Forecast _returnForecastResultForecastVal1 = new org.noip.wuidl.tourguide.api.wsdl.weather.Forecast();
            _returnForecastResultForecastVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-06-05T19:20:32.983+02:00"));
            _returnForecastResultForecastVal1.setWeatherID((short)24329);
            _returnForecastResultForecastVal1.setDesciption("Desciption2034933884");
            org.noip.wuidl.tourguide.api.wsdl.weather.Temp _returnForecastResultForecastVal1Temperatures = new org.noip.wuidl.tourguide.api.wsdl.weather.Temp();
            _returnForecastResultForecastVal1Temperatures.setMorningLow("MorningLow1500490139");
            _returnForecastResultForecastVal1Temperatures.setDaytimeHigh("DaytimeHigh2026608187");
            _returnForecastResultForecastVal1.setTemperatures(_returnForecastResultForecastVal1Temperatures);
            org.noip.wuidl.tourguide.api.wsdl.weather.POP _returnForecastResultForecastVal1ProbabilityOfPrecipiation = new org.noip.wuidl.tourguide.api.wsdl.weather.POP();
            _returnForecastResultForecastVal1ProbabilityOfPrecipiation.setNighttime("Nighttime1965636007");
            _returnForecastResultForecastVal1ProbabilityOfPrecipiation.setDaytime("Daytime-1953286168");
            _returnForecastResultForecastVal1.setProbabilityOfPrecipiation(_returnForecastResultForecastVal1ProbabilityOfPrecipiation);
            _returnForecastResultForecast.add(_returnForecastResultForecastVal1);
            _returnForecastResult.getForecast().addAll(_returnForecastResultForecast);
            _return.setForecastResult(_returnForecastResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
