
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.noip.wuidl.tourguide.api.wsdl.weather;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-05T19:20:32.909+02:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "Weather",
                      portName = "WeatherHttpPost",
                      targetNamespace = "http://ws.cdyne.com/WeatherWS/",
                      wsdlLocation = "http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL",
                      endpointInterface = "org.noip.wuidl.tourguide.api.wsdl.weather.WeatherHttpPost")
                      
public class WeatherHttpPostImpl implements WeatherHttpPost {

    /** The Constant LOG. */
    private static final Logger LOG = Logger.getLogger(WeatherHttpPostImpl.class.getName());

    /* (non-Javadoc)
     * @see org.noip.wuidl.tourguide.api.wsdl.weather.WeatherHttpPost#getWeatherInformation(*
     */
    public org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfWeatherDescription getWeatherInformation() { 
        LOG.info("Executing operation getWeatherInformation");
        try {
            org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfWeatherDescription _return = new org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfWeatherDescription();
            java.util.List<org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription> _returnWeatherDescription = new java.util.ArrayList<org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription>();
            org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription _returnWeatherDescriptionVal1 = new org.noip.wuidl.tourguide.api.wsdl.weather.WeatherDescription();
            _returnWeatherDescriptionVal1.setWeatherID((short)24606);
            _returnWeatherDescriptionVal1.setDescription("Description-401952476");
            _returnWeatherDescriptionVal1.setPictureURL("PictureURL1463001891");
            _returnWeatherDescription.add(_returnWeatherDescriptionVal1);
            _return.getWeatherDescription().addAll(_returnWeatherDescription);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.noip.wuidl.tourguide.api.wsdl.weather.WeatherHttpPost#getCityWeatherByZIP(java.lang.String  zip )*
     */
    public org.noip.wuidl.tourguide.api.wsdl.weather.WeatherReturn getCityWeatherByZIP(java.lang.String zip) { 
        LOG.info("Executing operation getCityWeatherByZIP");
        System.out.println(zip);
        try {
            org.noip.wuidl.tourguide.api.wsdl.weather.WeatherReturn _return = new org.noip.wuidl.tourguide.api.wsdl.weather.WeatherReturn();
            _return.setSuccess(false);
            _return.setResponseText("ResponseText-1469650798");
            _return.setState("State-1008155171");
            _return.setCity("City1545247646");
            _return.setWeatherStationCity("WeatherStationCity-167858345");
            _return.setWeatherID((short)-18323);
            _return.setDescription("Description-67573994");
            _return.setTemperature("Temperature2031321938");
            _return.setRelativeHumidity("RelativeHumidity49307937");
            _return.setWind("Wind-225295617");
            _return.setPressure("Pressure316195192");
            _return.setVisibility("Visibility-823441862");
            _return.setWindChill("WindChill-2059215187");
            _return.setRemarks("Remarks-189951466");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.noip.wuidl.tourguide.api.wsdl.weather.WeatherHttpPost#getCityForecastByZIP(java.lang.String  zip )*
     */
    public org.noip.wuidl.tourguide.api.wsdl.weather.ForecastReturn getCityForecastByZIP(java.lang.String zip) { 
        LOG.info("Executing operation getCityForecastByZIP");
        System.out.println(zip);
        try {
            org.noip.wuidl.tourguide.api.wsdl.weather.ForecastReturn _return = new org.noip.wuidl.tourguide.api.wsdl.weather.ForecastReturn();
            _return.setSuccess(false);
            _return.setResponseText("ResponseText-1124899898");
            _return.setState("State1107698039");
            _return.setCity("City-975189635");
            _return.setWeatherStationCity("WeatherStationCity-1894616679");
            org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfForecast _returnForecastResult = new org.noip.wuidl.tourguide.api.wsdl.weather.ArrayOfForecast();
            java.util.List<org.noip.wuidl.tourguide.api.wsdl.weather.Forecast> _returnForecastResultForecast = new java.util.ArrayList<org.noip.wuidl.tourguide.api.wsdl.weather.Forecast>();
            org.noip.wuidl.tourguide.api.wsdl.weather.Forecast _returnForecastResultForecastVal1 = new org.noip.wuidl.tourguide.api.wsdl.weather.Forecast();
            _returnForecastResultForecastVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-06-05T19:20:32.925+02:00"));
            _returnForecastResultForecastVal1.setWeatherID((short)2047);
            _returnForecastResultForecastVal1.setDesciption("Desciption662582823");
            org.noip.wuidl.tourguide.api.wsdl.weather.Temp _returnForecastResultForecastVal1Temperatures = new org.noip.wuidl.tourguide.api.wsdl.weather.Temp();
            _returnForecastResultForecastVal1Temperatures.setMorningLow("MorningLow594796230");
            _returnForecastResultForecastVal1Temperatures.setDaytimeHigh("DaytimeHigh1699168959");
            _returnForecastResultForecastVal1.setTemperatures(_returnForecastResultForecastVal1Temperatures);
            org.noip.wuidl.tourguide.api.wsdl.weather.POP _returnForecastResultForecastVal1ProbabilityOfPrecipiation = new org.noip.wuidl.tourguide.api.wsdl.weather.POP();
            _returnForecastResultForecastVal1ProbabilityOfPrecipiation.setNighttime("Nighttime-1379527954");
            _returnForecastResultForecastVal1ProbabilityOfPrecipiation.setDaytime("Daytime1208564265");
            _returnForecastResultForecastVal1.setProbabilityOfPrecipiation(_returnForecastResultForecastVal1ProbabilityOfPrecipiation);
            _returnForecastResultForecast.add(_returnForecastResultForecastVal1);
            _returnForecastResult.getForecast().addAll(_returnForecastResultForecast);
            _return.setForecastResult(_returnForecastResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
